server:
  port: 9004
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 60000
      password: 123456
jwt:
#  openssl rand -hex 32
  secret: 9fa543ab908887fa3011d3692a28b865eec519fd235881c85efcc2659b61aa00
  access-expiration: 900
  refresh-expiration: 7200